{% set name = "pyodesys" %}
{% set version = "0.14.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyodesys-{{ version }}.tar.gz
  sha256: 7a5320dbcadc33c2d2b83c48393c03b4bd97f76c9c9fb075d8dbd28faddd19f6

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - matplotlib-base >=2.2.5
    - notebook >=5.7.8
    - numpy >=1.16.4
    - python
    - scipy >=1.2.3
    - sym >=0.3.4
    - sympy >=1.5.1
    - pycvodes
    - pygslodeiv2  # [not win]
    - pyodeint
    - pytest

test:
  imports:
    - pyodesys
    - pyodesys.native
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bjodah/pyodesys
  summary: Straightforward numerical integration of ODE systems from Python.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ProfLeao
