{% set name = "pyodesys" %}
{% set version = "0.14.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyodesys-{{ version }}.tar.gz
  sha256: 16beceb5ca40c8ebe3271402486f1bbedd6a138c6a21ebad9e66e6e911c8dc6f

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - appdirs
    - cython
    - matplotlib-base >=2.2.5
    - notebook >=5.7.8
    - numpy >=1.16.4
    - pycvodes
    - pygslodeiv2  # [not win]
    - pyodeint
    - pytest
    - python
    - scipy >=1.2.3
    - sym >=0.3.4
    - sympy >=1.5.1

test:
  imports:
    - pyodesys
    - pyodesys.native
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bjodah/pyodesys
  summary: Straightforward numerical integration of ODE systems from Python.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ProfLeao
    - bjodah
